.TH RMW "1" "March 2021"
.SH NAME
rmw - remove files, safely
.SH SYNOPSIS
\fBrmw\fR \fI[OPTION]\fR... FILE...
.SH DESCRIPTION
\fBrmw\fR is a safe-delete utility that sends files to your "Desktop"
trash (or a completely separate folder). It can also restore files and permanently
delete files that were rmw'ed more than a certain (configurable) number of days ago.
.SH RESTORING FILES
There are different ways to restore a file, or multiple files.

Use the -s option to show a list of files that can be restored.

Use the -u option to restore the file(s) that were last removed by rmw.

Use the \fB\-z\fR (or \fB\-\-restore\fR) option
and specify the path to them in in the \fI<WASTE>/files\fR folder (wildcards ok).
e.g. '\fBrmw \-z ~/.local/share/Waste/files/foo*\fR'.
.SH PURGING
If purging is 'on', \fBrmw\fR will permanently delete files from the folders
specified in the configuration file after 'x' number of days.
Purging can be disabled by using '\fBpurge_after = 0\fR' in configuration file.
\fBrmw\fR will only check once per day if it's time to purge (use \fB\-g\fR to check more often).
Add the line '\fBforce_required\fR' in your \fBrmw\fR configuration
file to require \fB\-f\fR (\fB\-\-force\fR) to enable purge.

.SH OPTIONS
.TP
\fB\-c \-\-config\fR \fIfilename\fR
Use an alternate configuration file.
.TP
\fB\-f \-\-force\fR
Allow rmw to purge files in the background.
.TP
\fB\-g[N_DAYS] \-\-purge[=N_DAYS]\fR
If purging is enabled, rmw will permanently delete files from the
folders specified in the configuration file after 'x' number of days.
By default, purging is disabled ('purge_after' is set to '0' in the
configuration file). To enable, use a value greater than '0' (Example:
If '45' is specified, rmw will permanently delete files that have been
in the waste (or trash) for more than 45 days.

The value of 'purge_after' can be temporarily overridden by using -g
[N_DAYS] or --purge[=NDAYS] (Examples: -g90, --purge=90).

The time of the last automatic purge check is stored in `purge-time`,
located in $HOME/.local/share/rmw (or $XDG_DATA_HOME/rmw).
.TP
\fB\-e \-\-empty\fR
completely empty (purge) all waste folders.
.TP
\fB\-r, \-R, \-\-recursive\fR
option used for compatibility with rm (recursive operation is enabled by default)
.TP
\fB\-h \-\-help\fR
Display a help screen and exit.
.TP
\fB\-l \-\-list\fR
List waste directories.
.TP
\fB\-o \-\-orphaned\fR
Check for orphaned files (for maintenance tasks).
.TP
\fB\-s \-\-select\fR
Displays a list to select files to restore.
.TP
\fB\-u \-\-undo-last\fR
Undo last safe removal.
.TP
\fB\-m \-\-most-recent-list\fR
list most recently rmw'ed files
.TP
\fB\-v \-\-verbose\fR
Print extra information on the output.
.TP
\fB\-w \-\-warranty\fR
Display warranty information and exit.
.TP
\fB\-V \-\-version\fR
Display version and licensing information and exit.
.TP
\fB\-z \-\-restore\fR \fIpattern\fR
Restore files matching \fIpattern\fR.
.SH DIRECTORIES
The program's configuration file is stored in \fB~/.config/\fR.
The data files are written to \fB~/.local/share/rmw/\fR.
By default, the safe-removed files are stored in \fB~/.local/share/Waste/\fR.
.SH LICENCE
This program is published under the terms of the GNU General Public License,
version 2 or any later version, as published by the Free Software Foundation.
.SH AUTHOR
Written by Andy Alt, with contributions from others.
