filter_template: &filter_template
  only_if: "changesInclude(
    'src/*',
    'test/*',
    '**meson.build',
    '.cirrus.yml',
    '**.wrap'
    )"

common_meson_steps: &common_meson_steps
  build_script:
    - cd builddir && ninja -v
  test_script:
    - cd builddir && meson test -v --suite rmw

common_freebsd_steps: &common_freebsd_steps
  pkginstall_script:
    - pkg update -f
    - pkg install -y git meson ninja gettext pkgconf

freebsd_task:
  <<: *filter_template
  name: freebsd-13-3
  freebsd_instance:
    image_family: freebsd-13-3
  <<: *common_freebsd_steps
  setup_script:
    - meson setup builddir
  <<: *common_meson_steps

freebsd_task:
  <<: *filter_template
  name: freebsd-14-1
  freebsd_instance:
    image_family: freebsd-14-1
  <<: *common_freebsd_steps
  setup_script:
    - meson setup builddir
  <<: *common_meson_steps

arm_task:
  <<: *filter_template
  arm_container:
    image: andy5995/rmw:build-env-bookworm
  env:
    CIRRUS_CLONE_SUBMODULES: true
  setup_script:
    - meson setup builddir -Db_sanitize=none
  <<: *common_meson_steps

macos_task:
  <<: *filter_template
  name: macOS arm64
  macos_instance:
    image: ghcr.io/cirruslabs/macos-runner:sonoma
  env:
    CIRRUS_CLONE_SUBMODULES: true
  pkginstall_script:
    - brew install meson ninja ncurses
  setup_script:
    - meson setup builddir
  <<: *common_meson_steps
