# Define a template for tasks
filter_template: &filter_template
  only_if: "changesInclude(
    'src/**/**',
    '**meson.build',
    '.cirrus.yml'
    )"

freebsd_task:
  <<: *filter_template
  name: freebsd-13-3
  freebsd_instance:
    image_family: freebsd-13-3

  pkginstall_script:
    - pkg update -f
    - pkg install -y git meson ninja gettext pkgconf

  setup_script:
    - meson setup builddir
  build_script:
    - cd builddir && ninja -v
  test_script:
    - cd builddir && meson test -v --suite rmw
  test_fake_media_root:
    - cd builddir && meson test -v --setup=fake_media_root --suite rmw

arm_task:
  <<: *filter_template
  arm_container:
    image: andy5995/rmw-build-env:bookworm
  env:
    CIRRUS_CLONE_SUBMODULES: true
  setup_script:
    - meson setup builddir -Db_sanitize=none
  build_script:
    - cd builddir && ninja -v
  test_script:
    - cd builddir && meson test -v --suite rmw
  test_fake_media_root:
    - cd builddir && meson test -v --setup=fake_media_root --suite rmw

macos_task:
  <<: *filter_template
  name: macOS arm64
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-xcode:latest

  env:
    CIRRUS_CLONE_SUBMODULES: true

  pkginstall_script:
    - brew install meson ninja ncurses

  setup_script:
    - meson setup builddir -Dnls=false
  build_script:
    - cd builddir && ninja -v
  test_script:
    - cd builddir && meson test -v --suite rmw
  test_fake_media_root:
    - cd builddir && meson test -v --setup=fake_media_root --suite rmw
