freebsd_task:
  name: FreeBSD
  freebsd_instance:
    image_family: freebsd-13-1

  env:
    CIRRUS_CLONE_SUBMODULES: true

  pkginstall_script:
    - pkg update -f
    - pkg install -y meson ninja gettext pkgconf

  setup_script:
    - meson setup builddir
  build_script:
    - cd builddir && ninja -v
  test_script:
    - cd builddir && meson test -v --suite rmw
  test_fake_media_root:
    - cd builddir && meson test -v --setup=fake_media_root --suite rmw

arm_task:
  arm_container:
    image: andy5995/rmw-build-env:bullseye
  env:
    CIRRUS_CLONE_SUBMODULES: true
  setup_script:
    - meson setup builddir -Db_sanitize=none
  build_script:
    - cd builddir && ninja -v
  test_script:
    - cd builddir && meson test -v --suite rmw
  test_fake_media_root:
    - cd builddir && meson test -v --setup=fake_media_root --suite rmw

macos_task:
  name: macOS arm64
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-xcode:latest

  env:
    CIRRUS_CLONE_SUBMODULES: true

  pkginstall_script:
    - brew install meson ninja ncurses

  setup_script:
    - meson setup builddir -Dnls=false
  build_script:
    - cd builddir && ninja -v
  test_script:
    - cd builddir && meson test -v --suite rmw
  test_fake_media_root:
    - cd builddir && meson test -v --setup=fake_media_root --suite rmw
