=head1 NAME

lst - list items in the trash folder

=head1 SYNOPSIS

    lst [OPTION...] [PATH]

=head1 DESCRIPTION

The B<lst> command lists files that have been moved to a trash
location - i.e. "deleted". The output format is similar to C<ls -g>
with the deletion time appended to each line, in square brackets.

    $ lst
    [today, /home/user]
    -rw-r--r--  1 409K May 23  2025 'My account info.zip'       [16:35]

    [yesterday, /home/user]
    -rw-r--r--  1 411K Apr 16 15:21 'Peek 2026-04-16 15-21.gif' [09:28]
    -rw-r--r--  1 411K Apr 16 15:19 'Peek 2026-04-16 15-21.gif' [07:19]
    drwxrwxr-x  5 4.0K Dec 11  2025  perl5/                     [07:53]

Output rows are grouped by (deletion date, parent directory) then
sorted by (name ascending, deletion time descending).

The C<PATH> argument filters the list and defaults to the current
working directory. It may refer to an item that was itself previously
moved to the trash.

    $ lst deleteddir
    [2026-04-25, /home/user]
    drwxrwxr-x  5 4.0K Nov 11  2024  deleteddir                 [19:01]

    [2026-01-11, /home/user/deleteddir]
    -rwxrwxr-x  5 4.0K Dec 11  2025  my-file                    [15:42]

Filesystem specific trash folders may exist in addition to the C<$HOME>
trash folder (which is typically C<$XDG_DATA_HOME/Trash>). They are
created for performance reasons, to ensure that a "deletion" does not
require an expensive copy operation. This leads to the concept of the
I<current trash folder> for any given C<PATH>.

=head1 OPTIONS

=over

=item --all-items, -a

List all trash items in the current trash folder. Equivalent to
using C<--recursive> (see below) from a filesystem mount directory.

=item --all-trash, -A

List all trash items from all known trash locations. Equivalent to
using C<--all-items> at the top directory of each filesystem. Note that
this can be expensive as it requires probing and potientially awakening
slow external storage.

Raises an error when C<PATH> is given.

=item --interactive, -i

Run in Terminal User Interface (TUI) mode to interactively select and
restore items.

=item --trash-dir, -T

Print the current trash I<directory> instead of its contents. Can be
combined with C<--all-trash> to list all trash locations.

=item --recursive, -R

Recursively list deletions from C<PATH> and all of its subdirectories.

=back

=head1 FILES

Trash folder information may be read from F<$XDG_CONFIG_HOME/rmwrc> or
F<$HOME/.config/rmwrc>

=head1 SEE ALSO

L<rmw>(1)

The freedesktop.org Trash L<Specification|https://specifications.freedesktop.org/trash/latest>.

=head1 COPYRIGHT

License GPLv3+: GNU GPL version 3 or later L<https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.  There is NO
WARRANTY, to the extent permitted by law.
