=head1 NAME

lst - list items in trash folders

=head1 SYNOPSIS

    lst [OPTION...] [DIRECTORY]

=head1 DESCRIPTION

The B<lst> command lists files and/or directories which have been moved
to trash folders as defined by the freedesktop.org L<Trash
Specification|https://specifications.freedesktop.org/trash/latest>.

By default, output is limited to items removed from the current directory,
and is grouped by the day of deletion. Items are sorted by name (ascending)
followed by deletion time (descending).

    $ lst
    [today]
    -rw-r--r--  1 409K May 23  2025 'My account info.zip'       [16:35]

    [yesterday]
    -rw-r--r--  1 411K Apr 16 15:21 'Peek 2026-04-16 15-21.gif' [09:28]
    -rw-r--r--  1 411K Apr 16 15:19 'Peek 2026-04-16 15-21.gif' [07:19]
    drwxrwxr-x  5 4.0K Dec 11  2025  perl5/                     [07:53]

The C<DIRECTORY> argument can be used to list items from a different location.
This works even if the location itself was moved to the trash.

    $ lst /some/deleted/dir
    [yesterday]
    -rwxrwxr-x  5 4.0K Dec 11  2025  my-file                    [15:42]

=head1 OPTIONS

=over

=item --all, -a

Do not ignore items starting with a dot.

=item --every-directory, -e

List trash items moved from every directory of the (C<DIRECTORY>)
filesystem. Equivalent to using C<--recursive> (see below) from the
mount point.

=item --every-filesystem, -E

List trash items from every directory of every known trash location. Equivalent
to using C<--every-directory> at each filesystem root containing a trash
folder.  This option conflicts with an explicit C<DIRECTORY> argument.

=item --group-by, -G TYPE

Group entries by C<TYPE> which is one of:

=over

=item * day [default]

Group entries by the day they were moved.

=item * directory

Group entries by the directory they were moved from.

=back

=begin comment

=item --interactive, -i

Present the files for restoration using a Terminal User Interface
(TUI). Implies C<--restore>.

=end comment

=item --trash-dirs, -T

List trash folders instead of trash entries.

=item --recursive, -R

Recursively list entries which were moved from C<DIRECTORY> and
its subdirectories.

=back

=head1 FILES

Trash folder information may be read from F<$XDG_CONFIG_HOME/rmwrc> or
F<$HOME/.config/rmwrc>

=head1 SEE ALSO

L<rmw>(1)

=head1 COPYRIGHT

License GPLv3+: GNU GPL version 3 or later L<https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.  There is NO
WARRANTY, to the extent permitted by law.
