=head1 NAME

lst - list items moved to the trash

=head1 SYNOPSIS

    lst [OPTION...] [PATH]

=head1 DESCRIPTION

The B<lst> command lists the files and/or directories which have been
moved to a trash folder. The output format is similar to C<ls
-g> with the deletion time tacked on the end in brackets.

Items are grouped by their date of deletion and parent directory, and
then sorted by name (ascending) and time of deletion (descending).

    $ lst
    [today, /home/user]
    -rw-r--r--  1 409K May 23  2025 'My account info.zip'       [16:35]

    [yesterday, /home/user]
    -rw-r--r--  1 411K Apr 16 15:21 'Peek 2026-04-16 15-21.gif' [09:28]
    -rw-r--r--  1 411K Apr 16 15:19 'Peek 2026-04-16 15-21.gif' [07:19]
    drwxrwxr-x  5 4.0K Dec 11  2025  perl5/                     [07:53]

The C<PATH> argument filters the list of trash items and defaults to
the current working directory. It may refer to an item that was itself
previously moved to the trash.

    $ lst /some/deleteddir
    [2026-04-25, /some]
    drwxrwxr-x  5 4.0K Nov 11  2024  deleteddir                 [19:01]

    [2026-01-11, /some/deleteddir]
    -rwxrwxr-x  5 4.0K Dec 11  2025  my-file                    [15:42]

=head1 OPTIONS

=over

=item --all-items, -a

List all trash items from the C<PATH>-relevant trash folder. Equivalent
to using C<--recursive> (see below) from your C<$HOME> directory or a
filesystem mount point.

=item --all-trash, -A

List all trash items from all known trash locations. Equivalent
to using C<--all-items> at the top of each trash location.

=item --interactive, -i

Run in Terminal User Interface (TUI) mode to interactively select and
restore items.

=item --trash-paths, -T

List known trash I<locations> instead of trash contents. Raises an
error if a C<PATH> is provided.

=item --recursive, -R

Recursively list entries which were moved from C<PATH> and below.

=back

=head1 FILES

Trash folder information may be read from F<$XDG_CONFIG_HOME/rmwrc> or
F<$HOME/.config/rmwrc>

=head1 SEE ALSO

L<rmw>(1)

The freedesktop.org Trash L<Specification|https://specifications.freedesktop.org/trash/latest>.

=head1 COPYRIGHT

License GPLv3+: GNU GPL version 3 or later L<https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.  There is NO
WARRANTY, to the extent permitted by law.
