Document: rmw
Title: Debian rmw Manual
Author: <insert document author here>
Abstract: This manual describes what rmw is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/rmw/rmw.sgml.gz

Format: postscript
Files: /usr/share/doc/rmw/rmw.ps.gz

Format: text
Files: /usr/share/doc/rmw/rmw.text.gz

Format: HTML
Index: /usr/share/doc/rmw/html/index.html
Files: /usr/share/doc/rmw/html/*.html
