FROM ubuntu:focal
ARG DEBIAN_FRONTEND=noninteractive

RUN apt update \
  && apt install -y software-properties-common \
  && add-apt-repository ppa:git-core/ppa \
  && apt update \
  && apt-get upgrade -y \
  && apt-get install -y \
    gettext \
    git \
    libncurses-dev \
    pkg-config \
    python3-pip \
  && rm -rf /var/lib/apt/lists \
  && python3 -m pip install --upgrade pip
RUN python3 -m pip install meson ninja

RUN useradd -U rmwbuilder
RUN passwd -d rmwbuilder

CMD ["/bin/bash","-l"]
