FROM debian:bookworm
RUN apt-get update \
  && apt-get upgrade -y \
  && apt-get install -y \
    gettext \
    git \
    libncurses-dev \
    meson \
    ninja-build \
    pip \
  && rm -rf /var/lib/apt/lists

WORKDIR /rmw
RUN useradd -U rmwbuilder
RUN passwd -d rmwbuilder
RUN chown rmwbuilder:rmwbuilder /rmw

COPY ./docker/entrypoint-test.sh .
RUN chown rmwbuilder:rmwbuilder entrypoint-test.sh

CMD ["/bin/bash","-l"]
