FROM debian:bookworm
RUN apt-get update \
  && apt-get upgrade -y \
  && apt-get install -y \
    gettext \
    git \
    libglib2.0-dev \
    libncurses-dev \
    meson \
    ninja-build \
    pip \
  && rm -rf /var/lib/apt/lists

RUN useradd -U rmwbuilder
RUN passwd -d rmwbuilder

CMD ["/bin/bash","-l"]
