FROM alpine

RUN apk update
RUN apk add \
      gcc \
      gettext \
      git \
      linux-headers \
      meson \
      musl-dev \
      musl-fts-dev \
      musl-libintl \
      ncurses-dev

CMD ["/bin/sh","-l"]
