FROM debian:bullseye
RUN apt-get update \
  && apt-get upgrade -y \
  && apt-get install -y \
    gettext \
    libncurses-dev \
    pip \
  && rm -rf /var/lib/apt/lists
RUN python3 -m pip install meson ninja

WORKDIR /rmw
RUN useradd -U rmwbuilder
RUN passwd -d rmwbuilder
RUN chown rmwbuilder:rmwbuilder /rmw

COPY ./docker/entrypoint-test.sh .
RUN chown rmwbuilder:rmwbuilder entrypoint-test.sh

CMD ["/bin/bash","-l"]
