FROM alpine

RUN apk update && apk upgrade && \
    apk add \
      gcc \
      gettext \
      git \
      glib-dev \
      linux-headers \
      meson \
      musl-dev \
      musl-fts-dev \
      ncurses-dev

CMD ["/bin/sh","-l"]
