name: C/C++ CI

on:
  push:
    paths-ignore:
    - '**/*.md'
  pull_request:
    paths-ignore:
    - '**/*.md'

jobs:
  ubuntu:
    strategy:
      fail-fast: false
      matrix:
        arch: [x64, ppc64le, armv7, aarch64]
        os: [ubuntu-18.04, ubuntu-latest]
        compiler: [gcc, clang]
    runs-on: ${{ matrix.os }}
    env:
      TERM: xterm
    concurrency:
      group: ${{ github.head_ref }}
      cancel-in-progress: true
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get install -y gettext valgrind
    - run: sudo python3 -m pip install meson ninja
    - name: gcc
      if: ${{ matrix.compiler == 'gcc' }}
      env:
        CC: gcc
      run: sh ./.github/scripts/all_tests.sh
    - name: clang
      if: ${{ matrix.compiler == 'clang' }}
      env:
        CC: clang
      run: sh ./.github/scripts/all_tests.sh

  macos:
    runs-on: macos-latest
    env:
      PKG_CONFIG_PATH: "/usr/local/opt/ncurses/lib/pkgconfig:$PKG_CONFIG_PATH"
      TERM: xterm
    concurrency:
      group: ${{ github.head_ref }}
      cancel-in-progress: true
    steps:
    - uses: actions/checkout@v2
    - run: |
        brew update
        brew install ncurses meson
    - run: |
        meson builddir
        ninja -v -C builddir
        ninja -C builddir dist
