name: Docker Meson Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
    paths:
      - '.github/workflows/docker-meson.yml'
      - 'docker/Dockerfile-meson'
  pull_request:
    branches: [ "master" ]
    paths:
      - '.github/workflows/docker-meson.yml'
      - 'docker/Dockerfile-meson'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push test
        if: ${{ github.ref != 'refs/heads/master' }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile-meson
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/meson:debian-bullseye-testing
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/meson:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/meson:buildcache,mode=max
      -
        name: Build and push
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile-meson
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/meson:debian-bullseye
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/meson:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/meson:buildcache,mode=max
