name: MacOS
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

on:
  push:
    branches: master
    paths:
    - '**'
    - '!**.yml'
    - '!**/.github'
    - '!**.md'
    - '!docker/**'
    - '!packaging/**'
    - '**/macos.yml'
  pull_request:
    branches: master
    paths:
    - '**'
    - '!**.yml'
    - '!**/.github'
    - '!**.md'
    - '!docker/**'
    - '!packaging/**'
    - '**/macos.yml'

jobs:
  build:
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - name: brew-canfigger
          install_packages: canfigger
          setup_options: --wrap-mode nofallback
        - name: bundled-canfigger

    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: false

    - name: Show info
      run: |
        export -p
        echo '${{ toJSON(matrix) }}'

    - run: |
        brew update
        brew install \
          gettext \
          meson \
          ninja \
          ncurses \
          pkg-config \
          ${{ matrix.build.install_packages }}

    - name: Configure
      run: |
        # jpkanne of the Mesonbuild project recommends setting this outside of
        # the meson.build file.
        # "It would be better to pass those in from the outside with a
        # configuration argument. Usually setting build env things from within
        # build files is an antipattern"
        PKG_CONFIG_ARGS="-Dpkg_config_path=/opt/homebrew/opt/ncurses/lib/pkgconfig,/usr/local/opt/ncurses/lib/pkgconfig"
        meson setup builddir ${{ matrix.build.setup_options }} $PKG_CONFIG_ARGS
    - name: Build
      run: |
        cd builddir
        ninja -v
    - name: Test
      run: cd builddir && meson test -v
    - name: Test fake media root
      run: cd builddir && meson test -v --setup=fake_media_root --suite rmw
