name: Spellcheck Action

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  spellcheck:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        sudo apt-get install -y python3-pip
        sudo -H python3 -m pip install pyspelling

    - uses: rojopolis/spellcheck-github-actions@v0
      name: Spellcheck
