name: Spellcheck Action

on:
  push:
    branches: master
    paths:
    - '**/**.md'
    - '**/wordlist.txt'
    - '**/spellcheck.yml'
    - '**/spellcheck-config.yml'
  pull_request:
    branches: master
    paths:
    - '**/**.md'
    - '**/wordlist.txt'
    - '**/spellcheck.yml'
    - '**/spellcheck-config.yml'

jobs:
  spellcheck:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: rojopolis/spellcheck-github-actions@v0
      name: Spellcheck
      continue-on-error: false
      with:
        config_path: .github/spellcheck-config.yml
